In [1]:
import numpy as np

array = np.array([
[64.0, 580.0, 29.0],    
[66.0, 570.0, 33.0], 
[68.0, 590.0, 37.0], 
[69.0, 660.0, 46.0],
[73.0, 600.0, 55.0],
])

array

array([[ 64., 580.,  29.],
       [ 66., 570.,  33.],
       [ 68., 590.,  37.],
       [ 69., 660.,  46.],
       [ 73., 600.,  55.]])

In [2]:
# mean values of array
mean = np.mean(array, axis=0)
mean

array([ 68., 600.,  40.])

In [3]:
# covariance matrix
cov = np.cov(array.T)
cov

array([[  11.5 ,   50.  ,   34.75],
       [  50.  , 1250.  ,  205.  ],
       [  34.75,  205.  ,  110.  ]])

In [4]:
# invert the covariance matrix
cov_inv = np.linalg.inv(cov)

In [5]:
# Solution 1, in numpy only, calculate the Mahalanobis Distance between one vector of the array to the mean value vector
diff = array[0] - mean

mahalanobis_distance = np.dot(diff.T, cov_inv)
mahalanobis_distance = np.dot(mahalanobis_distance, diff)
mahalanobis_distance = np.sqrt(mahalanobis_distance)
mahalanobis_distance

1.443699755720487

In [6]:
# Solution 1, use scipy
from scipy.spatial import distance
mahalanobis_distance = distance.mahalanobis(array[0], mean, cov_inv)
display(mahalanobis_distance)

1.443699755720487